#### RNN

In [ ]:
import torch

In [ ]:
import torch.nn as nn

In [ ]:
embedding_matrix = nn.Embedding(3, 2)

In [ ]:
embedding_matrix._parameters

OrderedDict([('weight',
              Parameter containing:
              tensor([[ 0.6414, -0.3856],
                      [-0.2088, -0.1834],
                      [-0.8739, -0.6629]], requires_grad=True))])

Write a `embedding_matrix` equivalent to `torch.nn.Embedding`

In [ ]:
def embedding_matrix(n_element, n_latent_factors):
    return torch.randn(n_element, n_latent_factors)

In [ ]:
embedding_matrix(3, 2)

tensor([[ 1.3978, -1.4555],
        [ 0.4007,  0.7626],
        [ 0.4648,  0.7645]])

In [ ]:
linear = nn.Linear(4, 3)

In [ ]:
input_ = torch.arange(1, 13)

In [ ]:
input_ = input_.reshape(3, 4).float()

In [ ]:
input_

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
linear(input_)

tensor([[ 0.8945, -0.7074,  0.0330],
        [ 2.3729, -2.3590, -0.6585],
        [ 3.8514, -4.0106, -1.3500]], grad_fn=<AddmmBackward0>)

In [ ]:
class Linear:
    def __init__(self, in_features, out_features):
        self.in_features = in_features
        self.out_features = out_features
        self.w = torch.randn(n)
        pass