In [ ]:
import torch

In [ ]:
a = torch.arange(-5, 25)

In [ ]:
a.shape

torch.Size([30])

In [ ]:
a

tensor([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
        13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
a = torch.reshape(a, (6, 5))

In [ ]:
a

tensor([[-5, -4, -3, -2, -1],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

### Integer array indexing

In [ ]:
a

tensor([[-5, -4, -3, -2, -1],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [ ]:
a[[1, 4], [3, 2]]

tensor([ 3, 17])

In [ ]:
a

tensor([[-5, -4, -3, -2, -1],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [ ]:
a[[1], [3,]]

tensor([3])

In [ ]:
a

tensor([[-5, -4, -3, -2, -1],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [ ]:
a[range(a.shape[0]), [3, 0, 1, 4, 4, 0]]

tensor([-2,  0,  6, 14, 19, 20])