In [2]:
import torch

In [9]:
a = torch.arange(-5, 25)

In [10]:
a = torch.reshape(a, (6, 5))

In [11]:
a

tensor([[-5, -4, -3, -2, -1],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [26]:
a = torch.rand(3, 4) * 10

In [27]:
a

tensor([[1.0795, 6.8913, 1.5219, 7.4195],
        [6.7016, 3.5856, 1.9811, 2.3971],
        [2.3358, 6.7834, 7.9938, 2.2160]])

In [31]:
a.ndim, a.shape

(2, torch.Size([3, 4]))

In [29]:
torch.argmax(a, dim=0)

tensor([1, 0, 2, 0])

In [30]:
torch.argmax(a, dim=1)

tensor([3, 0, 2])