### 1. `randn`

In [1]:
import torch

Create a tensor that follows a normal distribution with mean 0 and variance 1

In [2]:
tensor = torch.randn(2, 3)

In [3]:
tensor

tensor([[-0.8603,  0.3597,  0.3738],
        [-0.5937,  1.4431,  0.5222]])

### 2. `randperm`

In [20]:
import torch

Create a random permutation from 0 to 6

In [21]:
idxs = torch.randperm(7)

In [22]:
idxs

tensor([1, 3, 5, 6, 2, 0, 4])

In [23]:
a = torch.tensor([1, 2, 3])

In [24]:
b = torch.tensor([4, 5, 6])

In [29]:
torch.stack((a,))

tensor([[1, 2, 3]])