### Deep Learning

In [ ]:
from PIL import Image

In [ ]:
def load_and_resize(path, size):
    return Image.open(path).resize(size)

In [ ]:
def func(layer, inp, out):
    add_log(layer, out)

In [ ]:
def add_hook(model):
    for l in model.layers:
        l.register_hook(func)

In [ ]:
from fastai.vision.all import *

In [ ]:
class _TestCallback(Callback):
    def __init__(self):
        self.preds = []
    
    def after_batch(self):
        self.preds.append(self.pred)

In [ ]:
CancelBatchException 

In [ ]:
x.clamp_max_(3)

In [ ]:
x.sub(3)

In [ ]:
x.argsort()

In [ ]:
x.normal_()

In [ ]:
lin.bias.grad.zero_()

In [ ]:
lin.bias.data.zero_()

In [ ]:
import torch.nn as nn

In [ ]:
nn.Parameter()

Parameter containing:
tensor([], requires_grad=True)

In [ ]:
optim.step()

In [ ]:
l1.weight

In [ ]:
model.children()

In [ ]:
optim.zero_grad()

In [ ]:
model(x_train)

In [ ]:
init.kaiming_normal_(layer1.weight)

In [ ]:
self.layers = nn.ModuleList(*layers)

In [ ]:
l1.register_forward_

In [ ]:
self.add_module()

In [ ]:
nn.Sequential(*layers)

In [ ]:
l1.weight.grad

In [ ]:
model.named_children()

In [ ]:
torch.randperm(0, 10)

In [ ]:
with torch.no_grad(): #code

In [ ]:
torch.clamp_min(x, min=2)

In [ ]:
import torch

In [ ]:
import torch.nn as nn

In [ ]:
weight = nn.Parameter(torch.randn(1))

In [ ]:
weight

Parameter containing:
tensor([-1.0121], requires_grad=True)

In [ ]:
class Model(nn.Module):
    def __init__(self, n_in, nh, n_out):
        super().__init__()
        self.layers = [
            nn.Linear(n_in, nh),
            nn.ReLU(),
            nn.Linear(nh, n_out)
            ]
    
    def forward(self, x):
        for l in self.layers:
            x = l(x)
        
        return x

In [ ]:
model = Model(784, 50, 10)

In [ ]:
list(model.children())

[]

In [ ]:
class DataLoader:
    def __init__(self, ds, bs):
        self.ds = ds
        self.bs = bs
    
    def __iter__(self):
        for i in range(0, len(self.ds), self.bs):
            yield self.ds[i:i+self.bs]

In [ ]:
def train_mode(model):
    model.train()

In [ ]:
def accuracy(pred, targ):
    idx_preds = torch.argmax(pred, dim=-1)
    return (idx_preds == targ).float().mean()

In [ ]:
weight = nn.Parameter(torch.randn(1))

In [ ]:
weight

Parameter containing:
tensor([-1.3684], requires_grad=True)

In [ ]:
class _Model(nn.Module):
    def __init__(self, layers):
        super().__init__()
        self.layers = nn.ModuleList(layers)
        self.act_means = [[] for _ in self.layers]
    
    def forward(self, x):
        for i, l in enumerate(self.layers):
            x = l(x)
            self.act_means[i].append(x.mean())

In [ ]:
class DataLoader:
    def __init__(self, ds, bs):
        self.ds = ds
        self.bs = bs
    
    def __iter__(self):
        for i in range(0, len(self.ds), self.bs):
            yield self.ds[i:i+self.bs]

In [ ]:
def mean_squared_error(pred, targ):
    error = 0.
    
    for i in range(len(targ)):
        error += (targ - pred)**2
    
    return error / len(targ)

In [ ]:
ReLU = nn.ReLU()

In [ ]:
class DotProduct(nn.Module):
    def __init__(self, n_users, n_movies, n_factors):
        self.user_factors = nn.Embedding(n_users, n_factors)
        self.movie_factors = nn.Embedding(n_movies, n_factors)

In [ ]:
def one_hot(idx, n_elements):
    zeros = torch.zeros(n_elements)
    zeros[idx] = 1
    return zeros

In [ ]:
one_hot(3, 5)

tensor([0., 0., 0., 1., 0.])

In [ ]:
text = ' . '.join([l.strip() for l in lines])

NameError: name 'lines' is not defined

In [ ]:
import torch.nn.functional as F

In [ ]:
class _LMModel3(nn.Module):
    def __init__(self, vocab_sz, n_hidden):
        self.i_h = nn.Embedding(vocab_sz, n_hidden)
        self.h_h = nn.Linear(n_hidden, n_hidden)
        self.h_o = nn.Linear(n_hidden, vocab_sz)
        self.h = 0.
    
    def forward(self, x):
        for i in range(3):
            self.h = self.h + F.relu(self.i_h(x[:, i]))
            self.h = F.relu(self.h_h(self.h))
        
        out = F.relu(self.h_o(self.h))
        self.h = self.h.detach()
        return out

In [ ]:
def accuracy(pred, targ):
    idx_preds = torch.argmax(pred, dim=-1)
    return (idx_preds == targ).float().mean()

In [ ]:
def covariance(x, y):
    prod = (x-x.mean())*(y-y.mean())
    return prod.mean()

In [ ]:
def binary(x):
    return x.exp() / (1+x.exp())

In [ ]:
class Hook:
    def __enter__(self, *args): print('hello')
    
    def __exit__(self, *args): print('goodbye')

In [ ]:
with Hook() as hook:
    print('...')

hello
...
goodbye


In [ ]:
def zero_weight(l):
    return l.weight.data.zero_()

In [ ]:
def to_half_precision(x):
    return x.half()

In [ ]:
class _ListContainer:
    def __init__(self, items):
        self.items = items
    
    def __getitem__(self, idxs):
        if isinstance(idxs[0], bool):
            assert len(idxs) == len(self.items)
            return [o for b, o in zip(idxs, self.items) if b]

In [ ]:
l = _ListContainer([1, 2, 3, 4, 5])

In [ ]:
l[[True, False, True, False, True]]

[1, 3, 5]

In [ ]:
_actual_noises = noises * _init_sigma

In [ ]:
noises = torch.randn(1, channel, height // 8, width // 8)

### bash

In [ ]:
${name^^}

In [ ]:
!!

In [ ]:
${name,,}

In [ ]:
foo=$(pwd)

In [ ]:
${id:3}

In [ ]:
$USER

In [ ]:
${id:1:5}

In [ ]:
echo ~shivon

In [ ]:
mkdir week_{1, 2, 3 }

In [ ]:
echo "5/2" | bc

In [ ]:
echo {z..k}

In [ ]:
echo {1..10}

In [ ]:
echo "scale=2; 5//2" | bc

In [ ]:
${#name}

In [ ]:
echo $(($x + $y))

In [ ]:
#!/bin/bash
echo "My name is $1"
echo "I work at $2"

In [ ]:
echo ${id:3}

In [ ]:
echo "5/2" | bc

### Docker

In [ ]:
version: 0.01

services:
    mongodb:
        image: mongo
        port:
            - 27017:27017

SyntaxError: invalid syntax (5489320.py, line 3)

### Pandas

In [ ]:
new_dict = {0: "Olga", 1: "Andrew", 2: "Nicole"}

In [ ]:
import pandas as pd

In [ ]:
df3 = pd.DataFrame({"name": new_dict})

In [ ]:
df3

name
0    Olga
1  Andrew
2  Nicole

### SciPy

In [ ]:
import numpy as np

In [ ]:
def f(x):
    return x**2 * np.sin(2*x) * np.exp(-x)

In [ ]:
blue = x[1:3:2, 0:3:2]

In [ ]:
red = x[:, 1:3:2]

In [ ]:
booleans = [True, False, False, True, False, False]

### Python

### SQL

SELECT training.accuracy, datasets.size FROM training, datasets WHERE training.dsets_id = datasets.id

### fastcore

In [ ]:
from fastcore.basics import *

In [ ]:
class _T(Stateful):
    def __init__(self):
        super().__init__()
        self.a = 1
        self._state['test'] = 2

In [ ]:
t = _T()

In [ ]:
t.__dict__

{'_state': {'test': 2}, 'a': 1}

In [ ]:
from fastcore.meta import *

In [ ]:
@use_kwargs_dict(xx=2)
def foo(a, b=1, **kwargs):
    pass

In [ ]:
import inspect

In [ ]:
inspect.signature(foo)

<Signature (a, b=1, *, xx=2)>

### Git

In [ ]:
git branch -a

In [ ]:
git  remote origin URL

In [ ]:
git merge name

### Pytest

In [ ]:
import pytest

In [ ]:
import unittest

In [ ]:
class TestFeature(unittest.TestCase):
    
    @pytest.mark.xfail
    def test_eq(self):
        self.assertEqual(a, b)

In [ ]:
@pytest.parame

### Python

In [ ]:
with open('test.txt') as f:
    f.write("the end...")

In [ ]:
from typing import Callable

In [ ]:
def foo() -> Callable[[int, int], int]:
    def add(x: int, y: int) -> int:
        return x + y
    
    return add

In [ ]:
x: set[str, ...] = {"a"}