In [ ]:
function add(x, y=10)
    return x + y
end

add (generic function with 2 methods)

In [ ]:
add(1)

11

In [ ]:
add(1, 2)

3

In [ ]:
A = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [ ]:
x = [1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [ ]:
a, b... = x

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [ ]:
a

1

In [ ]:
b

4-element Vector{Int64}:
 2
 3
 4
 5

In [ ]:
entity, interactor, boundary

In [ ]:
rand(3, 4)

3×4 Matrix{Float64}:
 0.243558  0.662273  0.541462  0.482947
 0.329086  0.247729  0.65549   0.00426791
 0.846807  0.179714  0.284179  0.379912

In [ ]:
zeros(7)

7-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [ ]:
x = :brain

:brain