In [ ]:
xs = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
xs

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
map(x -> x^2, xs)

3-element Vector{Int64}:
 1
 4
 9

In [ ]:
function add(x::Int, y::Int)
    return x + y
end

add (generic function with 1 method)

In [ ]:
var_b = 4

4

In [ ]:
!(var_b >= 2)

false

In [ ]:
collect(Float64, xs)

In [ ]:
struct Starship <: Vehicle
    n_engines
end

LoadError: UndefVarError: Vehicle not defined

In [ ]:
map(f, xs)

In [ ]:
1:3

1:3

In [ ]:
rockets = (one="falcon 1", two="falcon 9")

(one = "falcon 1", two = "falcon 9")

In [ ]:
rockets.one

"falcon 1"

In [ ]:
rockets.two

"falcon 9"

In [ ]:
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
push!(v, 1)

4-element Vector{Int64}:
 1
 2
 3
 1

In [ ]:
xs = zeros(5)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [ ]:
xs[2:4] = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
xs

5-element Vector{Float64}:
 0.0
 1.0
 2.0
 3.0
 0.0

In [ ]:
xs[2, :]

In [ ]:
xs[]

In [ ]:
try
    1/0
catch e
    println(e)
end

Inf

In [ ]:
abstract type Vehicle end

In [ ]:
struct Book
    name::String
end

In [ ]:
h = Book("A")

Book("A")

In [ ]:
h.name

"A"

In [ ]:
mutable struct Computer
    os::String
end