# Introduction

In [2]:
import numpy as np

In [8]:
a = np.arange(-3, 4)

In [13]:
a

array([-3, -2, -1,  0,  1,  2,  3])

Compare each element of `a` > `1` and return the correspond result in boolean

In [15]:
a > 1

array([False, False, False, False, False,  True,  True])

### `np.cumsum`

In [16]:
a = np.array([1, 2, 3, 4, 5])

In [17]:
a

array([1, 2, 3, 4, 5])

Compute the cumulative sum of each element in `x`

In [18]:
a.cumsum()

array([ 1,  3,  6, 10, 15])