### Deep Learning

In [ ]:
learn = Learner(dls, model, loss_func=MSELossFlat())

In [ ]:
dblock = DataBlock(blocks = [ImageBlock, MultiCategoryBlock],
                   get_x = get_x,
                   get_y = get_y)

In [ ]:
import torch

In [ ]:
def droput_layer(x, p):
    assert 0 <= p <= 1
    if p == 1: return torch.zeros_like(x)
    
    mask = (torch.rand(x.shape) > p).float()
    return (mask * x) / (1 - p)

In [ ]:
activations = torch.arange(16).reshape((4, 4))

In [ ]:
activations

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [ ]:
droput_layer(activations, 1)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [ ]:
droput_layer(activations, 0.2)

tensor([[ 0.0000,  1.2500,  0.0000,  3.7500],
        [ 5.0000,  6.2500,  7.5000,  8.7500],
        [10.0000,  0.0000, 12.5000, 13.7500],
        [15.0000,  0.0000,  0.0000,  0.0000]])

In [ ]:
from torch import nn

In [ ]:
model = nn.Sequential(
    nn.Linear(2, 4),
    nn.Linear(4, 3)
)

In [ ]:
(filter1 * small_part).sum() + (filter2 * small_part).sum()

In [ ]:
def max_pool(x):
    return torch.max(x)

In [ ]:
max_pool(activations)

tensor(15)

In [ ]:
def fill_normal(x):
    return x.normal_()

SyntaxError: invalid syntax (3334134017.py, line 1)

In [ ]:
def dropout_layer(x, dropout):
    assert 0 <= dropout <= 1
    
    if dropout == 1: return torch.zeros_like(x)
    
    mask = (torch.rand(x.shape) > dropout).float()
    return (x * mask) / (1 - dropout)

In [ ]:
activations = torch.arange(16).reshape((4, 4))

In [ ]:
activations

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [ ]:
dropout_layer(activations, 0.2)

tensor([[ 0.0000,  1.2500,  0.0000,  0.0000],
        [ 5.0000,  6.2500,  7.5000,  8.7500],
        [10.0000, 11.2500, 12.5000, 13.7500],
        [ 0.0000, 16.2500, 17.5000, 18.7500]])

In [ ]:
class DotProduct(nn.Module):
    
    def __init__(self, n_users, n_movies, n_factors):
        super().__init__()
        self.user_factors = torch.rand(n_users, n_factors)
        self.movie_factors = torch.rand(n_movies, n_factors)
    
    def forward(self, x):
        users = self.user_factors(x[:, 0])
        movies = self.movie_factors(x[:, 1])
        
        return (users*movies).sum()

In [ ]:
def fill_normal(x):
    return x.normal_(mean=0, std=0.01)

### Python

In [ ]:
a, b, (c, d)

In [ ]:
from collections import namedtuple

In [ ]:
EV2 = namedtuple('ElectricVehicle', ['efficient', 'make', 'price'], defaults=(100, 'Tesla', 200))

In [ ]:
EV2(2)

ElectricVehicle(efficient=2, make='Tesla', price=200)

In [ ]:
from fastcore.meta import *

In [ ]:
import inspect

In [ ]:
def bar(a, b:int=2, c:int=3):
    return a + b + c

In [ ]:
@delegates(bar)
def foo(c, a, **kwargs):
    return c + baz(a, **kwargs)

In [ ]:
inspect.signature(foo)

<Signature (c, a, *, b: int = 2)>

### SQL

In [ ]:
SELECT * names AS 'name' FROM files

In [ ]:
SELECT * users WHERE (name='shivon' AND rank=1) OR (rank=2)

In [ ]:
SELECT * FROM production.images

In [ ]:
SELECT * FROM users WHERE rank='one' OR rank=1

In [ ]:
SELECT * FROM files WHERE status='DELETED'

In [ ]:
SELECT * FROM users WHERE rank='one' AND files=6

### SymPy

In [ ]:
f.subs({'x': 3, 'y': 2*z})

### Pandas

In [ ]:
import pandas as pd

In [ ]:
ratings.groupby('title')['rating'].mean()

### Design Patterns

In [ ]:
class CustomerSupport:
    
    def __init__(self):
        supplier = Supplier()
        self.warehouse = Warehouse(supplier)
    
    def buy(self, product):
        return self.warehouse.check_available_product(product)