### Science

In [ ]:
conditioned response, population activity, evoke-stimulus, motor imagery

### Software

In [ ]:
from enum import Enum

In [ ]:
class Vehicle(Enum):
    FALCON_1 = "Falcon 1"
    FALCON_9 = "Falcon 9"

In [ ]:
class Colors(Enum):
    RED = "Red"
    ORANGE = "Orange"
    BLUE = "Blue"
    
    @property
    def is_hot(self):
        return self in [Colors.RED, Colors.ORANGE, Colors.BLUE]

In [ ]:
Colors.RED.is_hot

True

### AI

In [ ]:
import torch
from torch import nn
import torch.nn.functional as F

In [ ]:
import jax 

In [ ]:
modified_square = jax.jit(square)

In [ ]:
from jax import random

In [ ]:
key = random.PRNGKey(seed=42)

In [ ]:
from jax import grad

In [ ]:
dfdx = grad(f)
d2fdx = grad(dfdx)
d3fdx = grad(d2fdx)

In [ ]:
from jax import numpy as jnp

In [ ]:
xs = jnp.array([0, 1, 2, 3, 4, 5])

In [ ]:
xs

Array([0, 1, 2, 3, 4, 5], dtype=int32)

In [ ]:
new_xs = xs.at[2].set(100)

In [ ]:
new_xs

Array([  0,   1, 100,   3,   4,   5], dtype=int32)

In [ ]:
grad_loss = grad(loss)

In [ ]:
class PerformanceBenchmark:
    def __init__(self, pipe, dataset):
        self.pipe = pipe
        self.dataset = dataset
    
    def compute_memory(self):
        pass
    
    def compute_latency(self):
        pass
    
    def compute_accuracy(self):
        pass
    
    def compute(self):
        pass

In [ ]:
def to_uppercase(example):
    text = example["summary"].upper()
    return {"summary": text}

In [ ]:
from torch.nn.utils import clip_grad_norm_

In [ ]:
clip_grad_norm_(param_1)

In [ ]:
class MultiHeadAttention(nn.Module):
    def __init__(self, attention, d_model, n_heads):
        super().__init__()
        self.attention = attention
        self.d_head = d_model // n_heads
        self.d_model, self.n_heads = d_model, n_heads
        
        self.w_q = nn.Linear(d_model, d_model)
        self.w_k = nn.Linear(d_model, d_model)
        self.w_v = nn.Linear(d_model, d_model)
        
        self.mha_linear = nn.Linear(d_model, d_model)
        
    def split_heads(self, x):
        batch_size, seq_len, d_model = x.size()
        return x.view(batch_size, self.n_heads, seq_len, self.d_head)
    
    def concat_heads(self, x):
        batch_size, n_heads, seq_len, d_head = x.size()
        return x.view(batch_size, seq_len, self.d_model)
    
    def forward(self, pre_q, pre_k, pre_v):
        q, k, v = self.w_q(pre_q), self.w_k(pre_k), self.w_v(pre_v)
        
        q, k, v = self.split_heads(q), self.split_heads(k), self.split_heads(v)
        
        attn_output, attn_weights = self.attention(q, k, v)
        
        output = self.concat_heads(attn_output)
        output = self.mha_linear(output)
        
        return output, attn_weights

In [ ]:
xs

Array([0, 1, 2, 3, 4, 5], dtype=int32)

In [ ]:
xs.at[2].set(100)

Array([  0,   1, 100,   3,   4,   5], dtype=int32)

In [ ]:
def add_hook(model):
    for layer in model.layers:
        layer.register_forward_hook(add_log)

In [ ]:
dataset_samsum.map(to_uppercase)