### Python

In [1]:
class MetaStudent(type):
    pass

In [2]:
import numpy as np

In [3]:
np.where(x > 1, "Good", "bad")

NameError: name 'x' is not defined

In [4]:
class Atom:
    def __delattr__(self, k):
        pass

In [ ]:
x[1:2:3, :2:2]

In [5]:
import unittest

In [7]:
class MediumTestCase(unittest.TestCase):
    def test_avg(self):
        with self.assertRaises(TypeError) as err:
            avg()

In [8]:
from abc import ABC, abstractclassmethod

In [9]:
class Cashier(ABC):
    @abstractclassmethod
    def scan_item(self): pass

In [10]:
class HumanX(ABC):
    @abstractclassmethod
    def start_shift(self): pass

    @abstractclassmethod
    def take_break(self): pass

In [ ]:
class SelfServeMachine()

In [11]:
class Mercedez:
    @staticmethod
    def auto_drive():
        pass

In [ ]:
from typing import 

In [13]:
from enum import Enum, auto

In [15]:
class ImperialMeasure:
    CUP = 1
    TEASPOON = 1

In [16]:
from dataclasses import dataclass

In [20]:
from typing import Set

In [17]:
@dataclass
class Ingredient:
    name: str
    amount: float
    unit: ImperialMeasure

In [21]:
@dataclass
class Recipe:
    meats: Set[Ingredient]
    starches: Set[Ingredient]

In [22]:
from typing import TypeVar

In [25]:
T = TypeVar("T")

In [ ]:
APIResponse = Union[T, APIError]

In [ ]:
ls | tee output.txt

### Docker

In [ ]:
docker log monitor_app

In [ ]:
cat < h1.txt > h2.txt

In [ ]:
FROM WHERE SELECT

### Deep Learning

In [26]:
import torch
from torch import nn
import torch.nn.functional as F

In [28]:
from torch.nn import init

In [ ]:
init.kaiming_normal_(layer1.weight)

In [29]:
import pytorch_lightning as pl

In [30]:
class LitResNet(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.model = _model1
        self.loss_func = loss
    
    def training_step(self, batch, batch_idx):
        pred = self.model(x)
        loss = self.loss_func(pred, y)
        
        return loss

In [31]:
from torch.utils.data import Dataset

In [32]:
class PetDataset(Dataset):
    def __init__(self, data):
        self.data = data
    
    def __len__(self): return len(self.data)

    def __getitem__(self, idx):
        title = self.data[idx]['title']
        year_published = self.data[idx]['year_published']
        
        return title, year_published

In [ ]:
l1.register_forward_hook(add_visualize)

In [ ]:
text encoder, image encoder, projection head

In [ ]:
positional embedding, multi head, mask multihead, layer norm, skip connection, linear

In [ ]:
for t in range(n_steps):
    reward = calculate_reward(states[t], actions[t])
    v_mean = calculate_v(state[t+1]).mean()
    
    Q[t] = reward + gamma * v_mean

In [33]:
def probability_scores(image_embedding, text_embedding):
    image_embedding_norm = image_embedding.norm()
    text_embedding_norm = text_embedding.norm()
    
    image_embedding = image_embedding / image_embedding_norm
    text_embedding = text_embedding / text_embedding_norm
    
    scores = image_embedding @ text_embedding.T
    
    probs = F.softmax(scores, dim=-1)
    
    return probs

In [ ]:
tokens = tokenizier.encode(sentence)

In [ ]:
model.generate(tokens)

In [34]:
class EncoderLayer(nn.Module):
    def __init__(self, d_model, n_heads, d_ff, dropout):
        super().__init__()
        self.norm_1 = ResidualLayerNorm(d_model, dropout)
        self.norm_2 = ResidualLayerNorm(d_model, dropout)
        self.position_wise = PositionWiseFeedForward(d_model, d_ff, dropout)
        self.mha = MultiHeadAttention(d_model, n_heads)
    
    def forward(self, embeddings):
        mha_output, mha_attention_weights = self.mha(
            pre_q=embeddings, pre_k=embeddings, pre_v=embeddings
        )
        
        norm_1 = self.norm_1(x=mha_output, residual=embeddings)
        position_wise = self.position_wise(norm_1)
        norm_2 = self.norm_2(x=position_wise, residual=norm_1)
        
        return norm_2, mha_attention_weights

In [38]:
class Encoder(nn.Module):
    def __init__(self, d_model, n_heads, n_layers, d_ff, dropout):
        super().__init__()
        self.text_embedding = TextEmbedding(
            vocab_size=1000, d_model=d_model, padding_idx=0
        )
        
        self.positional_encoding = PositionalEncoding(d_model)
        
        self.encoder_layers = nn.ModuleList([
            EncoderLayer(
                d_model, n_heads, d_ff, dropout
            ) for _ in range(n_layers)
        ])
    
    def forward(self, tokens):
        embeddings = self.embeddings(tokens)
        embeddings = self.positional_encoding(embeddings)
        
        encoder_output = embeddings
        
        for encoder_layer in self.encoder_layers:
            encoder_output, encoder_attention_weights = encoder_layer(encoder_output)
        
        return encoder_output, encoder_attention_weights

In [39]:
def covariance(x, y):
    prod = (x-x.mean())*(y-y.mean())
    
    return prod.mean()

In [41]:
def variance(x):
    return (x-x.mean()).pow(2).mean()

In [59]:
preds = torch.tensor([-2, -1, 0, 1, 2]).float()

In [60]:
targs = torch.tensor([5, 5, 5, 5, 5]).float()

In [66]:
import torch

In [67]:
preds

tensor([-2., -1.,  0.,  1.,  2.])

In [68]:
targs

tensor([5., 5., 5., 5., 5.])

Write a function calculate the mean absolute error from scratch

In [69]:
def mean_absolute_error(preds, targs):
    return (preds-targs).abs().mean()

In [70]:
output = mean_absolute_error(preds, targs)

In [71]:
output

tensor(5.)

In [ ]:
def std(x):
    return (x-x.mean()).pow

In [ ]:
target_idxs = y_train[:3]

In [ ]:
sm_pred[[0, 1, 2], [...target_idxs]]

In [ ]:
def mae(x):
    return (x-x.mean()).abs().mean()

In [72]:
def variance(x):
    return (x-x.mean()).pow(2).mean()

In [ ]:
def regularize_activation(loss, activation, alpha):
    loss += loss + alpha*activation.pow(2).mean()

### RL

In [ ]:
state, action, next state, rewarda

In [35]:
def generate_transitions(model, env):
    state, _ = env.reset()
    state = torch.from_numpy(state)
    
    states = []
    actions = []
    next_states = []
    rewards = []
    
    while True:
        pred_actions = model(state)
        action = torch.argmax(pred_actions, dim=-1).item()
        
        next_state, reward, done, truncated, info = env.step(action)
        next_state = torch.from_numpy(next_state)
        
        states.append(state)
        actions.append(action)
        next_states.append(next_state)
        rewards.append(reward)

        if done: break
        
        state = next_state
    
    return states, actions, next_states, rewards

In [36]:
def convert_to_distribution(states):
    q_values = q_funciton(states)
    
    q_values = q_values.exp()
    z = q_values.sum(dim=-1)
    
    return q_values / z

In [37]:
nn.Embedding(num_embeddings=100, embedding_dim=5, padding_idx=5)

Embedding(100, 5, padding_idx=5)

In [3]:
import torch
import torch.nn.functional as F

In [4]:
x = torch.tensor(3.32)

In [12]:
y = torch.tensor(4.1)

In [15]:
torch.sigmoid(x - y)

tensor(0.3143)

In [17]:
from torch import nn
import torch.nn.functional as F

In [19]:
kl_loss = nn.KLDivLoss(reduction="batchmean")
# input should be a distribution in the log space
input = F.log_softmax(torch.randn(3, 5, requires_grad=True), dim=1)
# Sample a batch of distributions. Usually this would come from the dataset
target = F.softmax(torch.rand(3, 5), dim=1)
output = kl_loss(input, target)

In [20]:
kl_loss = nn.KLDivLoss(reduction="batchmean", log_target=True)
log_target = F.log_softmax(torch.rand(3, 5), dim=1)

In [23]:
input

tensor([[-0.4085, -2.4067, -3.2963, -2.0996, -2.4563],
        [-3.5734, -2.0205, -1.6307, -1.6248, -0.8061],
        [-1.5771, -2.5264, -2.4717, -2.0001, -0.7058]],
       grad_fn=<LogSoftmaxBackward0>)

In [22]:
log_target

tensor([[-1.8228, -1.4082, -1.7653, -1.5682, -1.5404],
        [-2.0124, -1.3858, -1.1972, -1.9692, -1.7452],
        [-2.1661, -1.7430, -1.5733, -1.3743, -1.3862]])

In [24]:
output = kl_loss(input, log_target)

In [25]:
output

tensor(0.3717, grad_fn=<DivBackward0>)