In [1]:
import numpy as np

In [22]:
names = np.array(["Shivon", "Josh", "Hunter"])

In [23]:
names

array(['Shivon', 'Josh', 'Hunter'], dtype='<U6')

In [24]:
f = lambda x: x[0]

Create a function `get_the_first_letter` that apply function `f` to each elements in `names` and return the correspond results

In [25]:
get_the_first_letter = np.vectorize(f)

In [26]:
get_the_first_letter(names)

array(['S', 'J', 'H'], dtype='<U1')

In [27]:
a = np.arange(0, 8)

In [28]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [34]:
a%4 == 0

array([ True, False, False, False,  True, False, False, False])

### Return the range

In [35]:
a = np.arange(0, 8)

In [43]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

Return all the elements of `y` that in the range $[1, 4]$

In [44]:
idxs = (a >=1)*(a <= 4)

In [45]:
a[idxs]

array([1, 2, 3, 4])