In [ ]:
import torch

In [ ]:
a = torch.arange(10)

In [ ]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = torch.arange(10)

In [ ]:
b

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.cat([a, b])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])