In [ ]:
import torch

In [ ]:
a = torch.arange(-2, 2)

In [ ]:
a

tensor([-2, -1,  0,  1])

Find the largest value in `a`

In [ ]:
a.max()

tensor(1)

### `torch.argmax()`

In [ ]:
a = torch.arange(1, 25)

In [ ]:
a = a.reshape(2, 4, 3)

In [ ]:
a

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])

In [ ]:
a.shape

torch.Size([2, 4, 3])

Explain how to compute it?

In [ ]:
torch.argmax(a, dim=0)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
a

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])

In [ ]:
a.shape

torch.Size([2, 4, 3])

In [ ]:
torch.argmax(a, dim=1)

tensor([[3, 3, 3],
        [3, 3, 3]])

In [ ]:
torch.argmax(a, dim=2)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]])