### Hello World

##### Example 1

Print the line `Hello world` as bellow

In [ ]:
println("Hello world")

Hello world


##### Example 2

Run the script `hello.jl` in command line

In [ ]:
julia hello.jl

LoadError: syntax: extra token "hello" after end of expression

### Variables

##### Example 1

In [ ]:
x, y = 2, 3

(2, 3)

Calculate the square of the sum of `x` and `y`

In [ ]:
(x+y)^2

25

##### Example 2

Define a constant variable valued 5

In [ ]:
const z = 5

5

In [ ]:
z

5

##### Example 3

In [ ]:
x = -2

-2

Check the type of variable `x`

In [ ]:
typeof(x)

Int64

In [ ]:
x

-2

In [ ]:
😃 = 1

1

##### Example 4

In [ ]:
o

LoadError: UndefVarError: o not defined

Create a function that works as bellow

In [ ]:
function add_one(x)
    x + 1
end

add_one (generic function with 1 method)

In [ ]:
add_one(90)

91

##### Example 5

Create an anonymous function (like lambda in python) that add two to each element in `y`

In [ ]:
z = x -> x + 2

LoadError: invalid redefinition of constant z

In [ ]:
map(x -> x+2, [1, 2, 3])

3-element Vector{Int64}:
 3
 4
 5

##### Example 6

In [ ]:
p = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
p

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
add_one

add_one (generic function with 1 method)

Apply function `add_one` to each element in `p`

In [ ]:
foreach(add_one, p)

##### Example 7

In [ ]:
some_number = 17

17

Write an `if` statement that print `Yes` if `some_number` is larger than 6

In [ ]:
if some_number > 6
    println("Yes")
end

Yes


##### Example 8

In [ ]:
var_a, var_b = 3, 4

(3, 4)

Print out "It's complicated" if `var_a` is greater than 1 or `var_b` is not less than 2

In [ ]:
if (var_a > 1) || (var_b >= 2)
    print("It's complicated")
end

It's complicated

##### Example 9

In [ ]:
var_b

4

Check whether `var_b` is not less than 2 but not using `>=`

In [ ]:
!(var_b < 2)

true

##### Example 10

In [ ]:
x, y

(-2, 3)

Create a non-anonymous function that works as bellow in one line

In [ ]:
f(x, y) = x + y

f (generic function with 1 method)

In [ ]:
f(x, y)

1

##### Example 11

In [ ]:
x, y

(-2, 3)

Create a function that calculate $3x^2 + 2y^2 - xy$ as bellow

In [ ]:
function poly(x, y)
    return 3x^2 + 2y^2 - x*y
end

poly (generic function with 1 method)

In [ ]:
poly(x, y)

36

##### Example 12

In [ ]:
\theta

LoadError: syntax: "\" is not a unary operator

In [ ]:
function f(x, ..., y):
    return nothing
end

LoadError: syntax: invalid identifier name "..."

### Primitive Types

##### Example 1

Explain why?

In [ ]:
2/3

0.6666666666666666

In [ ]:
2//3 == 2/3

false

**Explain** `2//3` is rational number which has infinite decimal points => not equal to 2/3 (rounded)

### Others

##### Example 1: Install a package

Install package `Sympy`

In [ ]:
import Pkg;

In [ ]:
Pkg.add("SymPy")

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


##### Example 2

Import package Sympy

In [ ]:
using SymPy

In [ ]:
x = Sym("x")

x

##### Example 3

Create a function $y$

In [ ]:
using SymPy

In [ ]:
y = SymFunction("y")

y

In [ ]:
y(x)

y(x)

In [ ]:
dy = diff(y(x), x)

d       
──(y(x))
dx      

In [ ]:
diff(dy, x)

  2      
 d       
───(y(x))
  2      
dx       

In [ ]:
typeof(dy)

Sym

In [ ]:
c = x^2 + y(x)^2 - 1

 2    2       
x  + y (x) - 1

In [ ]:
dc = diff(c, x)

             d       
2⋅x + 2⋅y(x)⋅──(y(x))
             dx      

In [ ]:
dydx = solve(dc, dy)

1-element Vector{Sym}:
 -x/y(x)

In [ ]:
typeof(dydx)

Vector{Sym} (alias for Array{Sym, 1})

In [ ]:
dydx[1]

-x  
────
y(x)

https://youtu.be/BnTYMOOPEzw?t=6357

### Partial Function

##### Example 4

In [ ]:
function g(a, b, c)
    return a + b + c
end

g (generic function with 1 method)

Define a function `f` that works as bellow

In [ ]:
f(x) = g(x, 2, 3)

f (generic function with 2 methods)

In [ ]:
f(1)

6

##### Example

In [ ]:
list = [1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

Assign value from `list` to `a`, `b` as bellow without explicitly define the index 

In [ ]:
a, b... = list

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [ ]:
a

1

In [ ]:
typeof(b)

Vector{Int64} (alias for Array{Int64, 1})

##### Example

Create a tuple

In [ ]:
rockets = (one = "falcon 1", two = "falcon 9")

(one = "falcon 1", two = "falcon 9")

In [ ]:
rockets.one

"falcon 1"

In [ ]:
rockets.two

"falcon 9"

In [ ]:
rockets[:two]

"falcon 9"

##### Example

In [ ]:
rockets = (one = "falcon 1", two = "falcon 9")

(one = "falcon 1", two = "falcon 9")

Access the key `two` of a tuple `rockets` by using bracket

In [ ]:
rockets[:two]

"falcon 9"

In [ ]:
:thing

:thing

In [ ]:
typeof(:thing)

Symbol

##### Example

Assign a Julia symbol named `brain` to variable `x`

In [ ]:
x = :brain

:brain

### Keywords Argument

Create a function takes two numbers and sum it up. As bellow

Hint: There's only one func.

In [ ]:
function add(a, b = 10)
    return a + b
end

add (generic function with 2 methods)

In [ ]:
add(1)

11

In [ ]:
add(1, 2)

3

### Array Types

##### Example 1

Create a matrix `A`

In [ ]:
A = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

##### Example

In [ ]:
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
v

3-element Vector{Int64}:
 1
 2
 3

Add a value `10` to vector `v` without specify the index

In [ ]:
push!(v, 10)

4-element Vector{Int64}:
  1
  2
  3
 10

In [ ]:
v

4-element Vector{Int64}:
  1
  2
  3
 10

In [ ]:
length(v)

4

In [ ]:
x = 1

1

In [ ]:
length(x)

1

In [ ]:
rand(1, 3)

1×3 Matrix{Float64}:
 0.969481  0.971624  0.970286

In [ ]:
A

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [ ]:
size(A)

(2, 3)

In [ ]:
size(v)

(4,)

In [ ]:
zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [ ]:
randn(10)

10-element Vector{Float64}:
 -0.401348324088007
 -0.170080784851108
  0.3056391780348198
 -0.896706843695948
  0.12747793701740387
 -0.8841619916337986
 -0.2933644982684619
 -0.6883985281549515
 -1.1114019235094095
 -0.6788492322828672

In [ ]:
rand(10)

10-element Vector{Float64}:
 0.6656011383750504
 0.07089014008818528
 0.14339924978480145
 0.798141844660147
 0.059007762577517275
 0.5433776190281081
 0.946073715447114
 0.23305498367778166
 0.13630127784550128
 0.8578536015066247

In [ ]:
sum( )

6

What are the difference between `using Statistics` and `import Statistics`

**Explain**
- `using Statistics`: import all the things that exported in package `Statistics`
- `import Statistics`: not import all the things that export

##### Example 

In [ ]:
xs = [1 2 3;
      4 5 6;
      7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [ ]:
xs

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

Return all values from row `2` to the last row without specify the row

In [ ]:
xs[2:end]

8-element Vector{Int64}:
 4
 7
 2
 5
 8
 3
 6
 9

Return all values of column `1`

In [ ]:
xs[:, 1]

3-element Vector{Int64}:
 1
 4
 7

Return all values of row `2`

In [ ]:
xs[2, :]

3-element Vector{Int64}:
 4
 5
 6

##### Example

In [ ]:
xs = zeros(5)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [ ]:
xs

5-element Vector{Float64}:
 0.0
 1.0
 2.0
 3.0
 0.0

Set the values of `xs`

In [ ]:
xs[2:4] = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
xs

5-element Vector{Float64}:
 0.0
 1.0
 2.0
 3.0
 0.0

### `map()`

##### Example 1

In [ ]:
xs = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
xs

3-element Vector{Int64}:
 1
 2
 3

Create an anonymous function that square a number, and apply that function to all elements in `xs` in one line

In [ ]:
map(x -> x^2, xs)

3-element Vector{Int64}:
 1
 4
 9

### Broadcasting

##### Example 2

In [ ]:
sin.(xs)

3-element Vector{Float64}:
 0.8414709848078965
 0.9092974268256817
 0.1411200080598672

In [ ]:
map(sin, xs)

3-element Vector{Float64}:
 0.8414709848078965
 0.9092974268256817
 0.1411200080598672

### Conditional Evaluation

##### Example 1

In [ ]:
xs = [1, 2, 3, 4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [ ]:
xs

4-element Vector{Int64}:
 1
 2
 3
 4

Loop through all elements in `xs` and print it

In [ ]:
for i in xs
    println(i)
end

1
2
3
4


##### Example 2

In [ ]:
xs = 1:3

1:3

In [ ]:
xs

1:3

Return a vector with given all the elements in `xs`

In [ ]:
v = collect(xs)

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
typeof(xs)

UnitRange{Int64}

### Exceptions

Do `1 / 0` and print the error

In [ ]:
try
    1 / 0
catch e
    println(e)
end

Inf

### Linear Algebra

### Types

In [ ]:
Int64

Int64

In [ ]:
Number

Number

In [ ]:
x = Int64

Int64

In [ ]:
y = Integer

Integer

##### Example 1

In [ ]:
x, y

(Int64, Integer)

Return `True` if `x` is a subtype of `y`

In [ ]:
x <: y

true

In [ ]:
"hoody"::String

"hoody"

In [ ]:
x::String = "hello"

LoadError: error in method definition: function Base.: must be explicitly imported to be extended

In [ ]:
n = 100

100

In [ ]:
n::Int = 100

LoadError: cannot set type for global n. It already has a value or is already set to a different type.

In [ ]:
xx = 1

1

##### Example 2

In [ ]:
function add(x, y)
    return x + y
end

add (generic function with 2 methods)

Add type annotations to function `add`. It expects all `Int` values.

In [ ]:
function add(x::Int, y::Int)
    return x + y
end

add (generic function with 2 methods)

In [ ]:
add(1, 2)

3

### Types

##### Example 1 

`Book` is immutable

In [ ]:
struct Book
    name::String
end

In [ ]:
homo_sapien = Book("Homo Sapien")

Book("Homo Sapien")

In [ ]:
homo_sapien.name

"Homo Sapien"

##### Example 2

In [ ]:
mutable struct Computer
    os::String
end

In [ ]:
c = Computer("XR")

Computer("XR")

In [ ]:
c.os

"XR"

In [ ]:
c.os = "Window"

"Window"

In [ ]:
c.os

"Window"

##### Example 3

Create an type that don't have property

In [ ]:
abstract type Vehicle end

In [ ]:
Vehicle

Vehicle

##### Example 4

In [ ]:
Vehicle

Vehicle

`Vehicle` is an type. Create a type `Starship` which is a subtype of `Vehicle`

In [ ]:
struct Starship <: Vehicle
    n_engines::Int
end

In [ ]:
starship = Starship(33)

Starship(33)

In [ ]:
starship.n_engines

33

### Dispatch

In [ ]:
moves(thing::Starship) = true

moves (generic function with 1 method)

In [ ]:
moves(thing) = false

moves (generic function with 2 methods)

In [ ]:
x = Starship(1)

Starship(1)

In [ ]:
moves(2)

false

##### Example 1

Create a function `is_string` as bellow. Will return `true` if the argument is a string, otherwise, return `false`, using dispatch

In [ ]:
is_string(thing::String) = true

is_string (generic function with 2 methods)

In [ ]:
is_string(thing) = false

is_string (generic function with 2 methods)

In [ ]:
is_string("hello"), is_string(1)

(true, false)