### Design ML Systems

In [ ]:
import random

In [ ]:
random.choice([1, 2 3, 4,])

In [ ]:
import torch

In [ ]:
def normalize(x):
    return (x - x.mean())/x.std()

In [ ]:
x = torch.rand((3, 2))

In [ ]:
x

tensor([[0.0109, 0.9486],
        [0.0361, 0.8321],
        [0.0900, 0.1692]])

In [ ]:
x_normalized = normalize(x)

In [ ]:
x_normalized

tensor([[-0.7921,  1.4125],
        [-0.7329,  1.1386],
        [-0.6061, -0.4200]])

In [ ]:
x_normalized.mean(), x_normalized.std()

(tensor(3.9736e-08), tensor(1.))

In [ ]:
def normalize(x, mean, std):
    return (x - mean)/std

In [ ]:
training_mean, training_std = x_train.mean(), x_train.std()

In [ ]:
x_train, x_valid = normalize(x_train, training_mean, training_std), normalize(x_valid, training_mean, trainingg_std)

In [ ]:
def relu(x):
    return x.clamp_min(0.)

In [ ]:
x = torch.randn((3, 2))

In [ ]:
x

tensor([[ 2.2029, -0.5614],
        [-0.2608,  0.6813],
        [-0.9447, -1.3339]])

In [ ]:
relu(x)

tensor([[2.2029, 0.0000],
        [0.0000, 0.6813],
        [0.0000, 0.0000]])

In [ ]:
def frobenius_norm(x):
    return (x*x).sum().sqrt()

In [ ]:
frobenius_norm(x)

tensor(2.8934)

In [ ]:
class Dataset:
    def __init__(self, x, y):
        self.x, self.y = x, y
        
    def __len__(self):
        return len(self.x)
    
    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

In [ ]:
from torch import nn

In [ ]:
def sigmoid_range(x, low, high):
    return nn.sigmoid(x) * (high - low) + low

In [ ]:
import PILImage

ModuleNotFoundError: No module named 'PILImage'

In [ ]:
seven_tensors = torch.stack([Image.open(o) for o in sevens])

In [ ]:
from PIL import Image

In [ ]:
seven_tensors = torch.stack([tensor(Image.open(o)) for o in senvens], dim=0)

In [ ]:
def one_hot(n_elements, idx):
    zeros = torch.zeros(n_elements)
    zeros[idx] = 1.
    return zeros

In [ ]:
one_hot(5, 3)

tensor([0., 0., 0., 1., 0.])

In [ ]:
from PIL import Image

In [ ]:
seven_tensors = torch.stack([tensor(Image.open(o) for o in sevens)], dim=0)

In [ ]:
def one_hot(n_elements, idx):
    zeros = torch.zeros(n_elements)
    zeros[idx] = 1.
    return zeros

In [ ]:
user_factors.T() @ one_hot(n_users, 3)

### Design Patterns

##### Bridge Patterns

In [ ]:
class Implementer:
    def 

##### Singleton


In [ ]:
class Database:
    _instance = None
    
    def __new__(cls):
        if not cls._instance:
            cls._instance = super().__new__(cls)
        
        return cls._instance

In [ ]:
db1 = Database()

In [ ]:
db2 = Database()

In [ ]:
id(db1) == id(db2)

True

In [ ]:
def distance(point_a, point: b):
    """
    Do something
    
    :param: point: 
    
    """

### Fastcore

In [ ]:
from fastcore.dispatch import *

In [ ]:
t = TypeDispatch([f2, f3])

In [ ]:
L().gotattr('id')

In [ ]:
from fastcore.test import *

In [ ]:
test_fail(f, contains='foo')

In [ ]:
L(nums).map(square)

In [ ]:
from fastcore.foundation import *

In [ ]:
b = [{'id': 15, 'name': 'nbdev'}, {'id': 17, 'name': 'fastcore'}]

In [ ]:
b

[{'id': 15, 'name': 'nbdev'}, {'id': 17, 'name': 'fastcore'}]

In [ ]:
L(b).attrgot('id')

(#2) [15,17]

In [ ]:
from fastcore.meta import *

In [ ]:
@funcs_kwargs
class DataBlock:
    _methods = ['splitter']

In [ ]:
dblock = DataBlock(splitter=lambda:1)

In [ ]:
dblock.splitter()

1

In [ ]:
import inspect

In [ ]:
def foo(a, b=1, **kwargs): pass

In [ ]:
inspect.signature(foo)

<Signature (a, b=1, **kwargs)>

In [ ]:
@use_kwargs_dict(d=2)
def foo(a, b=1, **kwargs): pass

In [ ]:
inspect.signature(foo)

<Signature (a, b=1, *, d=2)>

### Pandas

In [ ]:
import pandas as pd

In [ ]:
movies = pd.DataFrame(path1, **default_parameters, names=['movie', 'title'])