### ML Engineering

In [2]:
from airflow import DAG
from airflow.operators.python import PythonOperator

In [5]:
def func_1(re):
    re.push("x", 2)

In [6]:
def func_2(re):
    x = re.pull("x", tasks=["task_1"])
    y = x + 3
    re.push("y", t)

In [ ]:
with DAG(dag_id=dag_id, start_date=start_date) as dag:
    task_1 = PythonOperator(
        task_id="task_1",
        python_callable=func_1
    )
    task_2 = PythonOperator(
        task_id="task_2",
        python_callable=func_2
    )
    
    task_1 >> task_2

In [7]:
import great_expectations as ge

In [ ]:
df = ge.dataset.PandasDataset(data)

In [ ]:
df.expect_column_values_to_be_unique("id")

In [ ]:
@app.get("/blog")
def blog(page, published):
    pass

In [ ]:
[task_3, task_2] >> task_1

In [8]:
from airflow.operators.bash import BashOperator

In [ ]:
task_1 = BashOperator(
    task_id="task_1",
    bash_command="echo hello world"
)

In [9]:
from pydantic import BaseModel

In [10]:
class Blog(BaseModel):
    title: str
    desc: str

In [ ]:
@app.post("/blog")
def create_blog(blog: Blog):
    pass

In [12]:
from airflow.decorators import dag

In [ ]:
@dag(dag_id=dag_id, start_date=start_date)
def example():
    pass

In [13]:
from datetime import datetime

In [ ]:
with DAG(
    dag_id=dag_id,
    start_date=datetime(2023, 5, 31)
) as dag:
    task = PythonOperator(
        task_id="fuck_you",
        python_callable=say_hello
    )
    task 

In [15]:
from metaflow import FlowSpec, step, project

In [ ]:
@project(name="project_69")
class TrainFlow(FlowSpec):
    @step
    def start(self):
        self.next(self.train)
    
    @step
    def train(self):
        train()
        self.next(self.end)
    
    @step
    def end(self): pass

In [ ]:
@project(name="project_69")
class EvaluateFlow(FlowSpec):
    @step
    def start(self):
        self.next(self.evaluate)
    
    @step
    def evaluate(self):
        evaluate()
        self.next(self.end)
    
    @step
    def end(self): pass

In [ ]:
class TestFruit:
    def setup_method(self):
        self.fruit = Fruit("fuck_you")
    
    def test_fruit(self):
        assert self.fruit.name = "fuck_you"
    
    def teardown_method(self):
        del self.fruit

In [16]:
import functools

In [ ]:
result = functools.reduce(lambda x, y: x + y, numbers)

In [17]:
import time

In [ ]:
def performance(func):
    def inner_func():
        start_time = time.time()
        func()
        end_time = time.time()
    
    return inner_func

In [18]:
import pytest

In [ ]:
@pytest.mark.parametrize(
    ["input", "output"],
    ([1, 1], [2, 4])
)
def test_square(input, output):
    assert square(input) == output

In [ ]:
if some_number > 6
    print "yes"
end

### Engineering

In [ ]:
max(clock_idx + 1, n_microbatches)

In [ ]:
int* p_number{};

In [ ]:
&x;

In [ ]:
#include <iostream>

In [ ]:
class Book() {
    public:
        std::string title;
    
        Book(std::string aTitle) {
            title = aTitle;
        }
}

In [ ]:
api server, scheduler, control manager, ectd

In [ ]:
#include <iostream>
using namespace std;

In [ ]:
string numberToColor(int number) {
    string color;
    
    switch (number) {
        case 1:
            color = "red";
            break;
        case 2:
            color = "blue";
            break;
    }
    
    return color;
}

In [ ]:
int main() {
    int numbers[] = {1, 2, 3, 4, 5};
    
    for (int i = 0; i < 3; i++) {
        std::cout << numbers[i];
    }
    
    return 0;
}

In [ ]:
class Book() {
    string title;
    string author;
}

In [ ]:
int main() {
    int a = 69;
    int* p = &a;
    
    std::cout << *p;
    
    return 0;
}

In [19]:
num_gpus = 4

In [20]:
world_size = 16

In [21]:
process_to_gpu = []

In [23]:
for rank in range(world_size):
    gpu = rank % num_gpus
    process_to_gpu.append([rank, gpu])

In [24]:
process_to_gpu

[[0, 0],
 [1, 1],
 [2, 2],
 [3, 3],
 [4, 0],
 [5, 1],
 [6, 2],
 [7, 3],
 [8, 0],
 [9, 1],
 [10, 2],
 [11, 3],
 [12, 0],
 [13, 1],
 [14, 2],
 [15, 3]]

In [ ]:
step 1: partrition params
step 2: move to rank
step 3: init local optiim
step 4: sync optimizer-related variables
step 5: move to bucket

In [ ]:
step 1: fp16 and fp32 copy of the weight
step 2: forward and backward pass using fp16
step 3: cast weight to fp32
step 4: update using fp32

In [ ]:
clock_idx + 1 - 

In [25]:
import torch
from torch import nn
import torch.nn.functional as F

In [26]:
def wait_stream(source_stream, target_stream):
    # so source_stream will wait target_stream
    if isinstance(target_stream, torch.cuda.Stream):
        if isinstance(source_stream, torch.cuda.Stream):
            # GPU waits for GPU
            source_stream.wait_stream(target_stream)
        else:
            # CPU waits for GPU
            target_stream.syncrous()

In [ ]:
class Wait(torch.autograd.Function):
    @staticmethod
    def forward(ctx, prev_stream, next_stream, input):
        ctx.prev_stream = prev_stream
        ctx.next_stream = next_stream
        
        wait_stream(
            source_stream=next_stream,
            target_stream=prev_stream
        )
        
        return input

    @staticmethod
    def backward(ctx, grad_input):
        prev_stream = ctx.prev_stream
        next_stream = ctx.next_stream
        
        wait_stream(
            source_stream=prev_stream,
            target_stream=next_stream
        )
        
        grad_stream = (None, None)
        
        return grad_stream + grad_input

In [27]:
n_microbatches = 4

In [28]:
n_partritions = 3

In [35]:
for clock_idx in range(n_microbatches+n_partritions-1):
    start_partrition = max(clock_idx+1-n_microbatches, 0)
    end_partrition = min(clock_idx+1, n_partritions)
    
    for x in range(start_partrition, end_partrition):
        pass

In [ ]:
clock cycle 1: F_{1, 1}
clock cycle 2: F_{2, 1}, F_{1, 2}
clock cycle 3: F_{3, 1}, F_{2, 2}, F_{1, 3}

In [ ]:
CPU to GPU, CPU to CPU
GPU to GPU, GPU to CPU

In [ ]:
max(clock_idx + 1 - n_microbatches, 0)

In [ ]:
global memory > shared memory > thread

In [36]:
n_microbatches = 4
n_partritions = 3

In [37]:
n_clock_cycles = n_microbatches + 1 - n_partritions

In [ ]:
for clock_idx in range(n_clock_cycles):
    start_partrition = max(clock_idx + 1 - n_microbatches, 0)
    end_partrition = min(clock_idx + 1, n_partritions)
    
    for partrition_idx in range(start_partrition, end_partrition):
        microbatch_idx = 
        print(())

In [ ]:
(clock_idx+1, n_partritions)

In [ ]:
step 1: cpu memory
step 2: gpu memory
step 3: cpu to gpu
step 4: computation
step 5: gpu to cpu
step 6: gpu memory dellocation

In [ ]:
F_{i, j} completed before F_{i, j+1}
B_{i, j} completed before B_{i, j-1}

### AI

In [ ]:
class MultiplyConstant(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        ctx.input = input
        return input
    
    @staticmethod
    def backward(ctx, grad_input):
        return ctx.input + 1

In [ ]:
tokens = model.to_tokens(text)

In [ ]:
logits = model(tokens)

In [ ]:
log_probs = F.log_softmax(logits, dim=-1)

In [ ]:
target_tokens = tokens[:, 1:]

In [ ]:
predicted_log_probs = -log_probs.gather(target_tokens, dim=-1)

In [40]:
x = torch.tensor([1., 2., 3.], requires_grad=True)

In [49]:
import torch

In [50]:
x

tensor([1., 2., 3.], requires_grad=True)

Write a custom autograd function that returns the `input` in the forward pass and returns the gradient as `input + 1` in the backward pass.

In [51]:
class MultiplyConstant(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        ctx.input = input
        return input

    @staticmethod
    def backward(ctx, grad_input):
        return ctx.input + 1

In [52]:
output = MultiplyConstant.apply(x)

In [53]:
output

tensor([1., 2., 3.], grad_fn=<MultiplyConstantBackward>)

In [54]:
output.backward(output)

In [55]:
x.grad

tensor([4., 6., 8.])

In [ ]:
def probability_scores(image_embedding, text_embedding):
    image_norm = image_embedding.norm(dim=-1)
    image_embedding = image_embedding / image_norm
    
    text_norm = text_embedding.norm(dim=-1)
    text_embedding = text_embedding / text_norm
    
    similarities = torch.matmul(image_embedding, text_embedding.T)
    probs = F.softmax(similarities, dim=-1)
    
    return probs

In [57]:
import numpy as np

from gymnasium import Env
from gymnasium.spaces import Discrete, Box

In [ ]:
class ShowerEnv(Env):
    def __init__(self):
        super().__init__()
        self.action_space = Discrete(3)
        self.observation_space = Box(
            low=np.array([0]),
            high=np.array([100])
        )
    
    def reset(self):
        self.shower_length = 60
        self.temperature = 20
        return self.shower_length, self.temperature

In [ ]:
p, d, n, 

In [ ]:
class EncoderLayer(nn.Module):
    def __init__(self, d_model, n_heads, d_ff, dropout):
        super().__init__()
        self.mha = MultiHeadAttention(
            d_model=d_model,
            n_heads=n_heads
        )
        self.norm_1 = ResidualLayerNorm(
            d_model=d_model,
            dropout=dropout
        )