### Deep Learning

In [ ]:
def log_softmax(x):
    softmax = np.exp(x) / np.sum(np.exp(x))
    return np.log(softmax)

In [ ]:
import numpy as np

In [ ]:
inputs = np.arange(-5, 11)

In [ ]:
inputs

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
log_softmax(inputs)

array([-15.45867503, -14.45867503, -13.45867503, -12.45867503,
       -11.45867503, -10.45867503,  -9.45867503,  -8.45867503,
        -7.45867503,  -6.45867503,  -5.45867503,  -4.45867503,
        -3.45867503,  -2.45867503,  -1.45867503,  -0.45867503])

In [ ]:
def softmax(x):
    return np.exp(x)/(np.sum(np.exp(x)))

In [ ]:
softmax(inputs)

array([1.93367168e-07, 5.25626458e-07, 1.42880085e-06, 3.88388338e-06,
       1.05574896e-05, 2.86982322e-05, 7.80098831e-05, 2.12052848e-04,
       5.76419403e-04, 1.56687039e-03, 4.25919530e-03, 1.15776932e-02,
       3.14714330e-02, 8.55482245e-02, 2.32544184e-01, 6.32120630e-01])

In [ ]:
def mean_square_error(pred, actual):
    return ((actual - pred)**2)/pred.shape[0]

In [ ]:
def ReLU(x):
    return np.maximum(0, x)

In [ ]:
ReLU(inputs)

array([ 0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Python OOP

In [ ]:
class TextField:
    def __init__(self, name):
        self._name = name
    
    def __set__(self, instance, value):
        instance[self._name] = value

### Python

In [ ]:
def extra_decorator(func):
    def wrapper(*args, **kwargs):
        ...
        func(*args, **kwargs)
        ...
    return wrapper

### PyTest

In [ ]:
import pytest

In [ ]:
@pytest.mark.parametrize(
    ("test_input", "expected"),
    ([1, 1], [2, 4])
)
def test_square(test_input, expected):
    assert square(test_input) == expected

### Pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({'name': names})

NameError: name 'names' is not defined